import { Connection, IDatabaseDriver, Options } from "@mikro-orm/core";
import {
	Activity,
	ActivityFeed,
	Asset,
	AssetLocation,
	AssetLocationParent,
	AuthRole,
	AuthTask,
	AuthUser,
	Category,
	ComputerSpecifications,
	Config,
	Contact,
	Manufacturer,
	Network,
	NetworkConfigurations,
	Organization,
	ServiceDoneBy,
	ServiceJob,
	ServiceSchedule,
	Supplier,
	SupportRequest,
	SupportRequestField,
	SupportRequestTypeField,
	SupportRequestType,
} from "./entity";
import { Logger } from "../logging";

const ORMLogger = new Logger("orm");

const ORMConfig: Options<IDatabaseDriver<Connection>> = {
	entities: [
		AuthUser,
		AuthRole,
		AuthTask,
		Supplier,
		Contact,
		Organization,
		Asset,
		Manufacturer,
		AssetLocation,
		AssetLocationParent,
		Category,
		ComputerSpecifications,
		NetworkConfigurations,
		ServiceSchedule,
		Network,
		ServiceJob,
		ServiceDoneBy,
		Config,
		Activity,
		ActivityFeed,
		SupportRequest,
		SupportRequestField,
		SupportRequestTypeField,
		SupportRequestType,
	],
	type: "postgresql",
	clientUrl: process.env.DATABASE_URL || "postgres://postgres:abc123@192.168.1.22:5432/itim",
	debug: true,
	logger: ORMLogger.info,
	migrations: { emit: "js", pattern: /^[\w-]+\d+\.js$/ },
};

export { ORMConfig, ORMLogger };
