version: "3"
services:
  app:
    build: .
    volumes: 
      - .:/app
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - 3000:3000
  db:
    image: mysql
    environment:
      MYSQL_PASSWORD: abc123

